name: release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"

      - name: Reuse npm cache folder
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-npm-release-x2-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-release-x2-

      - run: npm install
      - run: npm run build

      - name: Get version
        id: version
        run: |
          npm run version
          echo ::set-output name=version::$(node ./scripts/version.js)

      - name: Set prerelease variable
        id: vars
        run: |
          echo ::set-output name=prerelease::${{ contains(steps.version.outputs.version, 'beta') }}
          echo ::set-output name=version::${{ steps.version.outputs.version }}

      - name: Log parsed version
        run: |
          node -v
          echo "version: ${{ steps.vars.outputs.version }}"
          echo "prerelease: ${{ steps.vars.outputs.prerelease }}"

      - name: add git tag
        run: |
          git tag ${{steps.vars.outputs.version}}
          git push origin ${{steps.vars.outputs.versionn}}

      # - name: Push tag
      #   uses: actions-ecosystem/action-push-tag@v1
      #   with:
      #     tag: ${{ github.event.inputs.version }}
      #     message: 'Pushing tag ${{ github.event.inputs.version }}'


      - run: npm publish --tag next
        if: steps.vars.outputs.prerelease == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npm publish
        if: steps.vars.outputs.prerelease == 'false'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # must run after the push
      # because it otherwise does not know
      # about the tag and add the old source code to the release.
      # This might be a bug.
      - uses: ncipollo/release-action@v1.14.0
        with:
          prerelease: ${{ steps.vars.outputs.prerelease }}
          tag: ${{github.event.inputs.version}}
          body: 'See Changelog of the RxDB repo'
          token: ${{ secrets.GITHUB_TOKEN }}
